app.name=FCRNGI_MFCIFINQ_SERVICE
server.port=8090
spring.profiles.active=mf-cif-inq
spring.application.name=mf-cif-inq
spring.jpa.generate-ddl=true
spring.jackson.serialization.write-dates-as-timestamps=false