app.name=FCRNGI_CUSTOMER_PROFILE_CIF_INQ_SERVICE
server.port=8080
spring.profiles.active=customer-profile-cif-inquiry
spring.application.name=customer-profile-cif-inquiry
spring.jpa.generate-ddl=false
spring.jackson.serialization.write-dates-as-timestamps=false